version: '3.8'

services:
  freshtomato-unblock:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: freshtomato-unblock
    # Use Docker volume instead of bind mount for auto-creation
    ports:
      # Secure: Bind only to NAS IP
      - "192.168.1.10:3000:3000"
    restart: on-failure:5
    environment:
      - NODE_ENV=production
      - DEFAULT_ROUTER_IP=192.168.1.1
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:?ADMIN_PASSWORD is required}
      - SESSION_SECRET=${SESSION_SECRET:?SESSION_SECRET is required}
      - DB_PATH=/app/data/app.db
      - SSH_KEYS_PATH=/app/data/ssh_keys
      - DEFAULT_SSH_USER=root
      - DEFAULT_TIMEOUT_MINUTES=1
      - MAX_TIMEOUT_MINUTES=60
    volumes:
      - freshtomato_data:/app/data
    extra_hosts:
      - "router.local:192.168.1.1"
    # Security hardening (Synology compatible)
    security_opt:
      - no-new-privileges:false  # Set to false for Synology compatibility
    # cap_drop:
    #   - ALL  # Commented out - too restrictive for Synology
    # Override Dockerfile USER directive - run as root like working containers
    user: "0:0"  # Root user (like your working NPM, Dozzle, Joplin containers)
    # Remove read_only for now as it may cause issues with Portainer
    # read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=50m
      # Removed ssh_keys tmpfs - conflicts with volume mount

volumes:
  freshtomato_data:
    # Docker-managed volume - auto-created with proper permissions
    driver: local